### ISSUE TITLE
Name Problems

### ISSUE THREAD

**Issue by sudo42** [GinaMuuss/redeliste#5]
Names containing Unicode characters (something like ß, ü or ³) are accepted by the interface, but will not show up in the list when pressing `raise`.

If a name equal to an already existing name is chosen, no error is shown, but one is not able to use `raise` and `lower`. The button is changed back to `lower` automatically after being activated.

**Comment by GinaMuuss** [comment]
Fixed unicode in docker and multiple use of a name is now allowed
